issuer: http://dex-idp:8888/auth

storage:
  type: memory

web:
  http: 0.0.0.0:8888

frontend:
  issuer: Fulcio in Docker Compose

expiry:
  signingKeys: "24h"
  idTokens: "1m"
  authRequests: "24h"

oauth2:
  responseTypes: [ "code" ]
  alwaysShowLoginScreen: true
  skipApprovalScreen: true

connectors:
- type: mockCallback
  id: mock
  name: AlwaysApprovesOIDCProvider

staticClients:
  - id: fulcio
    public: true
    name: 'Fulcio in Docker Compose'

# Dex's issuer URL + "/callback"
redirectURI: http://dex-idp:8888/auth/callback
